apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default     # 필요 시 namespace 지정
type: Opaque
stringData:
  # ⚠️ 아래의 값들은 실제 비밀번호가 아님
  # 배포 시 kubectl 명령으로 실제 값이 주입될 예정
  mysql-root-password: "<MYSQL_ROOT_PASSWORD>"
  mysql-user: "<MYSQL_USER>"
  mysql-password: "<MYSQL_PASSWORD>"
  mysql-database: "<MYSQL_DATABASE>"